12 <= 2 #false
2 == 2 #true
3 != 2 #true
1 <= 2 #true
2 == 3 #false
4 != 2 #true
12 >= 2 #true
3 == 3 #true
7 != 2 #true
5 != 7 #true

True or False  #true
False and False #true
True or True #false
False or False #false
False and True #false
True and True #true
False or True #true
True and False #false
False and False #true
True or True #false
False or False  #true
